#!/usr/bin/env bash
#
# It requires 'pypi' and 'testpypi' sections to be defined in .pypirc.

set -euo pipefail

if [[ "$*" == "test" ]]; then
  test="test"
else
  test=""
fi

for f in *.md; do
  pandoc -s -f gfm -t rst "$f" > "${f%.md}.rst"
done

pip install twine
rm -rf dist/*
python setup.py package || true
twine upload -r "${test}pypi" --skip-existing dist/* || true

for f in *.md; do
  rm -f "${f%.md}.rst"
done
