#!/usr/bin/env bash

set -euo pipefail

if [[ "$*" == "test" ]]; then
  test="test"
else
  test=""
fi

for f in *.md; do
  pandoc -s -f gfm -t rst "$f" > "${f%.md}.rst"
done

rm -f dist/*
python setup.py package || true
twine upload -r "${test}pypi" --skip-existing dist/* || true

for f in *.md; do
  rm -f "${f%.md}.rst"
done
